name: comment display

on: 
  issue_comment:
    types: [created] # コメント新規記入時のみ。編集(edited)では動かさない

jobs:
  display:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{github.event_name}}'
      - run: echo '${{toJSON(github.event)}}'

  comment:
    # issue_commentへのコメントで@devinから始まるかどうか
    if: github.event_name == 'issue_comment' &&
        contains(github.event.comment.html_url, '/issues/') && 
        startsWith(github.event.comment.body, '@devin')
    runs-on: ubuntu-latest
    steps:
    - run: echo "input comment (${{ github.event.comment.body }})"
